import time

NUM_USERS = 20
NUM_DEVICES = 10
MAX_NUM_DEVICES_PER_USER = 2
MIN_NUM_DEVICES_PER_USER = 1
PERC_DESKTOP = 50
PERC_IOS = 20
PERC_ANDROID = 20
PERC_MOBILE_BROWSER = 5
PERC_TABLET_BROWSER = 5
RANDOM_SEED = 1 #time.time()
